/**
 * Game Cards Definition
 * ゲーム全体のカード定義
 */

import type { Card, RoundCard } from "@/lib/types";

export const ALL_CARDS: Card[] = [
  // === 初期公共職場（ラウンド1から利用可能） ===
  {
    id: "quarry",
    name: "採石場",
    cost: 0,
    effect: "draw_card_1",
    cardType: "building",
    assetValue: 0,
    category: "public",
    icon: "⛏️",
  },
  {
    id: "mine",
    name: "鉱山",
    cost: 0,
    effect: "gain_coins_6_multi",
    cardType: "building",
    assetValue: 0,
    category: "public",
    icon: "⛰️",
    allowMultipleWorkers: true,
  },
  {
    id: "school",
    name: "学校",
    cost: 0,
    effect: "hire_worker_training",
    cardType: "building",
    assetValue: 0,
    category: "public",
    icon: "🏫",
  },
  {
    id: "carpenter",
    name: "大工",
    cost: 0,
    effect: "build_card",
    cardType: "building",
    assetValue: 0,
    category: "public",
    icon: "🪚",
  },

  // === ラウンド追加公共職場 ===
  {
    id: "shop",
    name: "露店",
    cost: 0,
    effect: "gain_coins_6",
    cardType: "building",
    assetValue: 0,
    category: "public",
    icon: "🏪",
  },
  {
    id: "market",
    name: "市場",
    cost: 0,
    effect: "gain_coins_12",
    cardType: "building",
    assetValue: 0,
    category: "public",
    icon: "🛒",
  },
  {
    id: "high_school",
    name: "高等学校",
    cost: 0,
    effect: "hire_to_4_workers",
    cardType: "building",
    assetValue: 0,
    category: "public",
    icon: "🎓",
  },
  {
    id: "supermarket",
    name: "スーパーマーケット",
    cost: 0,
    effect: "gain_coins_18",
    cardType: "building",
    assetValue: 0,
    category: "public",
    icon: "🏬",
  },
  {
    id: "university",
    name: "大学",
    cost: 0,
    effect: "hire_to_5_workers",
    cardType: "building",
    assetValue: 0,
    category: "public",
    icon: "🎓",
  },
  {
    id: "department_store",
    name: "百貨店",
    cost: 0,
    effect: "gain_coins_24",
    cardType: "building",
    assetValue: 0,
    category: "public",
    icon: "🏢",
  },
  {
    id: "vocational_school",
    name: "専門学校",
    cost: 0,
    effect: "hire_worker_instant",
    cardType: "building",
    assetValue: 0,
    category: "public",
    icon: "🏫",
  },
  {
    id: "expo",
    name: "万博",
    cost: 0,
    effect: "gain_coins_30",
    cardType: "building",
    assetValue: 0,
    category: "public",
    icon: "🎪",
  },

  // === プレイヤー建物カード（私有職場） ===

  // === プレイヤー建物カード（私有職場） ===
  // 合計73枚、27種類

  // 芋畑 ×6 (cost:1, asset:6)【農業】
  {
    id: "potato_field_1",
    name: "芋畑",
    cost: 1,
    effect: "discard_1_gain_8",
    cardType: "building",
    assetValue: 6,
    category: "private",
    buildingTag: "agriculture",
    icon: "🥔",
  },
  {
    id: "potato_field_2",
    name: "芋畑",
    cost: 1,
    effect: "discard_1_gain_8",
    cardType: "building",
    assetValue: 6,
    category: "private",
    buildingTag: "agriculture",
    icon: "🥔",
  },
  {
    id: "potato_field_3",
    name: "芋畑",
    cost: 1,
    effect: "discard_1_gain_8",
    cardType: "building",
    assetValue: 6,
    category: "private",
    buildingTag: "agriculture",
    icon: "🥔",
  },
  {
    id: "potato_field_4",
    name: "芋畑",
    cost: 1,
    effect: "discard_1_gain_8",
    cardType: "building",
    assetValue: 6,
    category: "private",
    buildingTag: "agriculture",
    icon: "🥔",
  },
  {
    id: "potato_field_5",
    name: "芋畑",
    cost: 1,
    effect: "discard_1_gain_8",
    cardType: "building",
    assetValue: 6,
    category: "private",
    buildingTag: "agriculture",
    icon: "🥔",
  },
  {
    id: "potato_field_6",
    name: "芋畑",
    cost: 1,
    effect: "discard_1_gain_8",
    cardType: "building",
    assetValue: 6,
    category: "private",
    buildingTag: "agriculture",
    icon: "🥔",
  },

  // 食堂 ×2 (cost:1, asset:8)
  {
    id: "cafeteria_1",
    name: "食堂",
    cost: 1,
    effect: "gain_coins_20_pay_10_agriculture_discount",
    cardType: "building",
    assetValue: 8,
    category: "private",
    icon: "🍽️",
  },
  {
    id: "cafeteria_2",
    name: "食堂",
    cost: 1,
    effect: "gain_coins_20_pay_10_agriculture_discount",
    cardType: "building",
    assetValue: 8,
    category: "private",
    icon: "🍽️",
  },

  // 鉄工所 ×3 (cost:1, asset:8)
  {
    id: "ironworks_1",
    name: "鉄工所",
    cost: 1,
    effect: "draw_card_3_industry_discount",
    cardType: "building",
    assetValue: 8,
    category: "private",
    icon: "🔧",
  },
  {
    id: "ironworks_2",
    name: "鉄工所",
    cost: 1,
    effect: "draw_card_3_industry_discount",
    cardType: "building",
    assetValue: 8,
    category: "private",
    icon: "🔧",
  },
  {
    id: "ironworks_3",
    name: "鉄工所",
    cost: 1,
    effect: "draw_card_3_industry_discount",
    cardType: "building",
    assetValue: 8,
    category: "private",
    icon: "🔧",
  },

  // 墓地 ×2 (cost:1, asset:8)【鍵】売却不可、終了時ボーナス
  {
    id: "graveyard_1",
    name: "墓地",
    cost: 1,
    effect: "none",
    cardType: "building",
    assetValue: 8,
    category: "private",
    buildingTag: "key",
    cannotSell: true,
    endGameBonus: "graveyard_bonus",
    icon: "⚰️",
  },
  {
    id: "graveyard_2",
    name: "墓地",
    cost: 1,
    effect: "none",
    cardType: "building",
    assetValue: 8,
    category: "private",
    buildingTag: "key",
    cannotSell: true,
    endGameBonus: "graveyard_bonus",
    icon: "⚰️",
  },

  // 宮大工 ×5 (cost:1, asset:8)
  {
    id: "palace_carpenter_1",
    name: "宮大工",
    cost: 1,
    effect: "discard_2_gain_25",
    cardType: "building",
    assetValue: 8,
    category: "private",
    icon: "🏯",
  },
  {
    id: "palace_carpenter_2",
    name: "宮大工",
    cost: 1,
    effect: "discard_2_gain_25",
    cardType: "building",
    assetValue: 8,
    category: "private",
    icon: "🏯",
  },
  {
    id: "palace_carpenter_3",
    name: "宮大工",
    cost: 1,
    effect: "discard_2_gain_25",
    cardType: "building",
    assetValue: 8,
    category: "private",
    icon: "🏯",
  },
  {
    id: "palace_carpenter_4",
    name: "宮大工",
    cost: 1,
    effect: "discard_2_gain_25",
    cardType: "building",
    assetValue: 8,
    category: "private",
    icon: "🏯",
  },
  {
    id: "palace_carpenter_5",
    name: "宮大工",
    cost: 1,
    effect: "discard_2_gain_25",
    cardType: "building",
    assetValue: 8,
    category: "private",
    icon: "🏯",
  },

  // 旧市街 ×3 (cost:2, asset:10)【鍵】売却不可
  {
    id: "old_town_1",
    name: "旧市街",
    cost: 2,
    effect: "vp_token_discount",
    cardType: "building",
    assetValue: 10,
    category: "private",
    buildingTag: "key",
    cannotSell: true,
    icon: "🏘️",
  },
  {
    id: "old_town_2",
    name: "旧市街",
    cost: 2,
    effect: "vp_token_discount",
    cardType: "building",
    assetValue: 10,
    category: "private",
    buildingTag: "key",
    cannotSell: true,
    icon: "🏘️",
  },
  {
    id: "old_town_3",
    name: "旧市街",
    cost: 2,
    effect: "vp_token_discount",
    cardType: "building",
    assetValue: 10,
    category: "private",
    buildingTag: "key",
    cannotSell: true,
    icon: "🏘️",
  },

  // 建築会社 ×2 (cost:2, asset:10)
  {
    id: "construction_company_1",
    name: "建築会社",
    cost: 2,
    effect: "gain_goods_2_vp_1",
    cardType: "building",
    assetValue: 10,
    category: "private",
    icon: "🏢",
  },
  {
    id: "construction_company_2",
    name: "建築会社",
    cost: 2,
    effect: "gain_goods_2_vp_1",
    cardType: "building",
    assetValue: 10,
    category: "private",
    icon: "🏢",
  },

  // 菜園 ×4 (cost:2, asset:10)【農業】
  {
    id: "vegetable_garden_1",
    name: "菜園",
    cost: 2,
    effect: "draw_card_2_need_mine",
    cardType: "building",
    assetValue: 10,
    category: "private",
    buildingTag: "agriculture",
    icon: "🥬",
  },
  {
    id: "vegetable_garden_2",
    name: "菜園",
    cost: 2,
    effect: "draw_card_2_need_mine",
    cardType: "building",
    assetValue: 10,
    category: "private",
    buildingTag: "agriculture",
    icon: "🥬",
  },
  {
    id: "vegetable_garden_3",
    name: "菜園",
    cost: 2,
    effect: "draw_card_2_need_mine",
    cardType: "building",
    assetValue: 10,
    category: "private",
    buildingTag: "agriculture",
    icon: "🥬",
  },
  {
    id: "vegetable_garden_4",
    name: "菜園",
    cost: 2,
    effect: "draw_card_2_need_mine",
    cardType: "building",
    assetValue: 10,
    category: "private",
    buildingTag: "agriculture",
    icon: "🥬",
  },

  // 食品工場 ×8 (cost:2, asset:12)【工業】
  {
    id: "food_factory_1",
    name: "食品工場",
    cost: 2,
    effect: "gain_coins_20_pay_10",
    cardType: "building",
    assetValue: 12,
    category: "private",
    buildingTag: "industry",
    icon: "🍞",
  },
  {
    id: "food_factory_2",
    name: "食品工場",
    cost: 2,
    effect: "gain_coins_20_pay_10",
    cardType: "building",
    assetValue: 12,
    category: "private",
    buildingTag: "industry",
    icon: "🍞",
  },
  {
    id: "food_factory_3",
    name: "食品工場",
    cost: 2,
    effect: "gain_coins_20_pay_10",
    cardType: "building",
    assetValue: 12,
    category: "private",
    buildingTag: "industry",
    icon: "🍞",
  },
  {
    id: "food_factory_4",
    name: "食品工場",
    cost: 2,
    effect: "gain_coins_20_pay_10",
    cardType: "building",
    assetValue: 12,
    category: "private",
    buildingTag: "industry",
    icon: "🍞",
  },
  {
    id: "food_factory_5",
    name: "食品工場",
    cost: 2,
    effect: "gain_coins_20_pay_10",
    cardType: "building",
    assetValue: 12,
    category: "private",
    buildingTag: "industry",
    icon: "🍞",
  },
  {
    id: "food_factory_6",
    name: "食品工場",
    cost: 2,
    effect: "gain_coins_20_pay_10",
    cardType: "building",
    assetValue: 12,
    category: "private",
    buildingTag: "industry",
    icon: "🍞",
  },
  {
    id: "food_factory_7",
    name: "食品工場",
    cost: 2,
    effect: "gain_coins_20_pay_10",
    cardType: "building",
    assetValue: 12,
    category: "private",
    buildingTag: "industry",
    icon: "🍞",
  },
  {
    id: "food_factory_8",
    name: "食品工場",
    cost: 2,
    effect: "gain_coins_20_pay_10",
    cardType: "building",
    assetValue: 12,
    category: "private",
    buildingTag: "industry",
    icon: "🍞",
  },

  // 宝くじ ×2 (cost:2, asset:10)
  {
    id: "lottery_1",
    name: "宝くじ",
    cost: 2,
    effect: "gain_coins_25",
    cardType: "building",
    assetValue: 10,
    category: "private",
    icon: "🎫",
  },
  {
    id: "lottery_2",
    name: "宝くじ",
    cost: 2,
    effect: "gain_coins_25",
    cardType: "building",
    assetValue: 10,
    category: "private",
    icon: "🎫",
  },

  // 養殖場 ×6 (cost:2, asset:12)【農業】
  {
    id: "fish_farm_1",
    name: "養殖場",
    cost: 2,
    effect: "gain_goods_hand_size",
    cardType: "building",
    assetValue: 12,
    category: "private",
    buildingTag: "agriculture",
    icon: "🐟",
  },
  {
    id: "fish_farm_2",
    name: "養殖場",
    cost: 2,
    effect: "gain_goods_hand_size",
    cardType: "building",
    assetValue: 12,
    category: "private",
    buildingTag: "agriculture",
    icon: "🐟",
  },
  {
    id: "fish_farm_3",
    name: "養殖場",
    cost: 2,
    effect: "gain_goods_hand_size",
    cardType: "building",
    assetValue: 12,
    category: "private",
    buildingTag: "agriculture",
    icon: "🐟",
  },
  {
    id: "fish_farm_4",
    name: "養殖場",
    cost: 2,
    effect: "gain_goods_hand_size",
    cardType: "building",
    assetValue: 12,
    category: "private",
    buildingTag: "agriculture",
    icon: "🐟",
  },
  {
    id: "fish_farm_5",
    name: "養殖場",
    cost: 2,
    effect: "gain_goods_hand_size",
    cardType: "building",
    assetValue: 12,
    category: "private",
    buildingTag: "agriculture",
    icon: "🐟",
  },
  {
    id: "fish_farm_6",
    name: "養殖場",
    cost: 2,
    effect: "gain_goods_hand_size",
    cardType: "building",
    assetValue: 12,
    category: "private",
    buildingTag: "agriculture",
    icon: "🐟",
  },

  // 会計事務所 ×1 (cost:3, asset:12)【鍵】売却不可、終了時ボーナス
  {
    id: "accounting_office_1",
    name: "会計事務所",
    cost: 3,
    effect: "gain_coins_4_per_good",
    cardType: "building",
    assetValue: 12,
    category: "private",
    buildingTag: "key",
    cannotSell: true,
    endGameBonus: "accounting_office_bonus",
    icon: "📊",
  },

  // 観光牧場 ×2 (cost:3, asset:14)【農業】
  {
    id: "tourist_ranch_1",
    name: "観光牧場",
    cost: 3,
    effect: "build_facility_draw_2",
    cardType: "building",
    assetValue: 14,
    category: "private",
    buildingTag: "agriculture",
    icon: "🐄",
  },
  {
    id: "tourist_ranch_2",
    name: "観光牧場",
    cost: 3,
    effect: "build_facility_draw_2",
    cardType: "building",
    assetValue: 14,
    category: "private",
    buildingTag: "agriculture",
    icon: "🐄",
  },

  // 研究所 ×2 (cost:3, asset:16)
  {
    id: "research_lab_1",
    name: "研究所",
    cost: 3,
    effect: "draw_card_2_vp_1",
    cardType: "building",
    assetValue: 16,
    category: "private",
    icon: "🔬",
  },
  {
    id: "research_lab_2",
    name: "研究所",
    cost: 3,
    effect: "draw_card_2_vp_1",
    cardType: "building",
    assetValue: 16,
    category: "private",
    icon: "🔬",
  },

  // 鉄道駅 ×2 (cost:3, asset:18)【鍵】売却不可、終了時ボーナス
  {
    id: "train_station_1",
    name: "鉄道駅",
    cost: 3,
    effect: "discard_2_draw_4",
    cardType: "building",
    assetValue: 18,
    category: "private",
    buildingTag: "key",
    cannotSell: true,
    endGameBonus: "train_station_bonus",
    icon: "🚉",
  },
  {
    id: "train_station_2",
    name: "鉄道駅",
    cost: 3,
    effect: "discard_2_draw_4",
    cardType: "building",
    assetValue: 18,
    category: "private",
    buildingTag: "key",
    cannotSell: true,
    endGameBonus: "train_station_bonus",
    icon: "🚉",
  },

  // プレハブ工務店 ×2 (cost:3, asset:12)
  {
    id: "prefab_builder_1",
    name: "プレハブ工務店",
    cost: 3,
    effect: "draw_goods_4_next_round",
    cardType: "building",
    assetValue: 12,
    category: "private",
    icon: "🏗️",
  },
  {
    id: "prefab_builder_2",
    name: "プレハブ工務店",
    cost: 3,
    effect: "draw_goods_4_next_round",
    cardType: "building",
    assetValue: 12,
    category: "private",
    icon: "🏗️",
  },

  // 地球建設 ×3 (cost:4, asset:16)
  {
    id: "earth_construction_1",
    name: "地球建設",
    cost: 4,
    effect: "build_2_draw_3",
    cardType: "building",
    assetValue: 16,
    category: "private",
    icon: "🌍",
  },
  {
    id: "earth_construction_2",
    name: "地球建設",
    cost: 4,
    effect: "build_2_draw_3",
    cardType: "building",
    assetValue: 16,
    category: "private",
    icon: "🌍",
  },
  {
    id: "earth_construction_3",
    name: "地球建設",
    cost: 4,
    effect: "build_2_draw_3",
    cardType: "building",
    assetValue: 16,
    category: "private",
    icon: "🌍",
  },

  // 醸造所 ×2 (cost:4, asset:18)【農業】
  {
    id: "brewery_1",
    name: "醸造所",
    cost: 4,
    effect: "draw_card_4",
    cardType: "building",
    assetValue: 18,
    category: "private",
    buildingTag: "agriculture",
    icon: "🍺",
  },
  {
    id: "brewery_2",
    name: "醸造所",
    cost: 4,
    effect: "draw_card_4",
    cardType: "building",
    assetValue: 18,
    category: "private",
    buildingTag: "agriculture",
    icon: "🍺",
  },

  // 植物園 ×1 (cost:4, asset:22)【鍵】売却不可、終了時ボーナス
  {
    id: "botanical_garden_1",
    name: "植物園",
    cost: 4,
    effect: "none",
    cardType: "building",
    assetValue: 22,
    category: "private",
    buildingTag: "key",
    cannotSell: true,
    endGameBonus: "botanical_garden_bonus",
    icon: "🌺",
  },

  // 造船所 ×3 (cost:4, asset:20)【工業】
  {
    id: "shipyard_1",
    name: "造船所",
    cost: 4,
    effect: "build_card_vp_1",
    cardType: "building",
    assetValue: 20,
    category: "private",
    buildingTag: "industry",
    icon: "🚢",
  },
  {
    id: "shipyard_2",
    name: "造船所",
    cost: 4,
    effect: "build_card_vp_1",
    cardType: "building",
    assetValue: 20,
    category: "private",
    buildingTag: "industry",
    icon: "🚢",
  },
  {
    id: "shipyard_3",
    name: "造船所",
    cost: 4,
    effect: "build_card_vp_1",
    cardType: "building",
    assetValue: 20,
    category: "private",
    buildingTag: "industry",
    icon: "🚢",
  },

  // 工業団地 ×2 (cost:5, asset:22)
  {
    id: "industrial_park_1",
    name: "工業団地",
    cost: 5,
    effect: "discard_3_draw_6",
    cardType: "building",
    assetValue: 22,
    category: "private",
    icon: "🏭",
  },
  {
    id: "industrial_park_2",
    name: "工業団地",
    cost: 5,
    effect: "discard_3_draw_6",
    cardType: "building",
    assetValue: 22,
    category: "private",
    icon: "🏭",
  },

  // 博物館 ×1 (cost:5, asset:34)【鍵】売却不可
  {
    id: "museum_1",
    name: "博物館",
    cost: 5,
    effect: "draw_card_3",
    cardType: "building",
    assetValue: 34,
    category: "private",
    buildingTag: "key",
    cannotSell: true,
    icon: "🏛️",
  },

  // 遊園地 ×2 (cost:5, asset:24)
  {
    id: "amusement_park_1",
    name: "遊園地",
    cost: 5,
    effect: "gain_coins_8",
    cardType: "building",
    assetValue: 24,
    category: "private",
    icon: "🎡",
  },
  {
    id: "amusement_park_2",
    name: "遊園地",
    cost: 5,
    effect: "gain_coins_8",
    cardType: "building",
    assetValue: 24,
    category: "private",
    icon: "🎡",
  },

  // 輸出港 ×1 (cost:5, asset:24)【鍵】売却不可、終了時ボーナス
  {
    id: "export_port_1",
    name: "輸出港",
    cost: 5,
    effect: "build_free_under_10",
    cardType: "building",
    assetValue: 24,
    category: "private",
    buildingTag: "key",
    cannotSell: true,
    endGameBonus: "export_port_bonus",
    icon: "⚓",
  },

  // 石油コンビナート ×2 (cost:6, asset:28)【工業】
  {
    id: "oil_complex_1",
    name: "石油コンビナート",
    cost: 6,
    effect: "gain_goods_2or3",
    cardType: "building",
    assetValue: 28,
    category: "private",
    buildingTag: "industry",
    icon: "🛢️",
  },
  {
    id: "oil_complex_2",
    name: "石油コンビナート",
    cost: 6,
    effect: "gain_goods_2or3",
    cardType: "building",
    assetValue: 28,
    category: "private",
    buildingTag: "industry",
    icon: "🛢️",
  },

  // 投資銀行 ×1 (cost:6, asset:30)【鍵】売却不可、終了時ボーナス
  {
    id: "investment_bank_1",
    name: "投資銀行",
    cost: 6,
    effect: "none",
    cardType: "building",
    assetValue: 30,
    category: "private",
    buildingTag: "key",
    cannotSell: true,
    endGameBonus: "investment_bank_bonus",
    icon: "🏦",
  },

  // 大聖堂 ×3 (cost:10, asset:50)【鍵】売却不可
  {
    id: "cathedral_1",
    name: "大聖堂",
    cost: 10,
    effect: "none",
    cardType: "building",
    assetValue: 50,
    category: "private",
    buildingTag: "key",
    cannotSell: true,
    icon: "⛪",
  },
  {
    id: "cathedral_2",
    name: "大聖堂",
    cost: 10,
    effect: "none",
    cardType: "building",
    assetValue: 50,
    category: "private",
    buildingTag: "key",
    cannotSell: true,
    icon: "⛪",
  },
  {
    id: "cathedral_3",
    name: "大聖堂",
    cost: 10,
    effect: "none",
    cardType: "building",
    assetValue: 50,
    category: "private",
    buildingTag: "key",
    cannotSell: true,
    icon: "⛪",
  },
];

// === 消費財カード（30枚） ===
export const CONSUMABLE_CARDS: Card[] = Array.from({ length: 30 }, (_, i) => ({
  id: `goods_${i + 1}`,
  name: "消費財",
  cost: 0,
  effect: "none",
  cardType: "goods",
  icon: "📦",
}));

// カード効果の説明
export const CARD_EFFECT_DESCRIPTIONS: Record<string, string> = {
  // 公共職場
  draw_card_1: "建物カード1枚引く",
  gain_coins_6_multi: "1枚捨て→$6（複数回可）",
  hire_worker_training: "労働者+1（研修中、次ラウンドから）",
  build_card: "手札から建物を建てる",
  gain_coins_6: "1枚捨て→$6（家計から）",
  gain_coins_12: "2枚捨て→$12（家計から）",
  hire_to_4_workers: "労働者を4人にする",
  gain_coins_18: "2枚捨て→$18（家計から）",
  hire_to_5_workers: "労働者を5人にする",
  gain_coins_24: "3枚捨て→$24（家計から）",
  hire_worker_instant: "労働者+1（即座に使える）",
  gain_coins_30: "3枚捨て→$30（家計から）",

  // 私有職場
  discard_1_gain_8: "手札を一枚捨てて家計から$8取る",
  gain_coins_20_pay_10_agriculture_discount:
    "家計から$20取り、$10返す。【農業】の建物を建てているならコスト-1",
  draw_card_3_industry_discount:
    "建物カード3枚引く。所有している【工業】建物一つにつきコスト-1",
  discard_2_gain_25: "手札を二枚捨てて家計から$25取る",
  vp_token_discount: "勝利点トークンを五枚以上持っていればコスト-4",
  gain_goods_2_vp_1: "消費財2枚+勝利点トークン1枚",
  draw_card_2_need_mine: "建物カード2枚引く（鉱山に配置必要）",
  gain_coins_20_pay_10: "家計から$20取り、$10返す",
  gain_coins_25: "家計から$25取る",
  gain_goods_hand_size: "手札0枚→消費財3枚、1枚→2枚、2枚→1枚",
  gain_coins_4_per_good: "手札の消費財1枚につき$4",
  build_facility_draw_2: "施設建物を建て、カード2枚引く",
  draw_card_2_vp_1: "建物カード2枚+勝利点トークン1枚",
  discard_2_draw_4: "手札2枚捨て→建物カード4枚",
  draw_goods_4_next_round: "消費財4枚（次ラウンド開始時に手札へ）",
  build_2_draw_3: "建物2つ建て、手札空なら3枚引く",
  draw_card_4: "建物カード4枚引く",
  none: "特殊効果なし（得点のみ）",
  build_card_vp_1: "建物を建て、勝利点トークン1枚",
  discard_3_draw_6: "手札3枚捨て→建物カード6枚",
  draw_card_3: "建物カード3枚引く",
  gain_coins_8: "家計から$8取る",
  build_free_under_10: "資産価値$10以下の建物を無料で建てる",
  gain_goods_2or3: "消費財なし→2枚、あり→3枚",

  // 終了時ボーナス
  graveyard_bonus: "終了時手札が無いなら+8点",
  accounting_office_bonus: "終了時に勝利点トークンから得られる得点を2倍にする",
  train_station_bonus: "終了時建物を6つ以上所有していれば+18点",
  botanical_garden_bonus: "終了時【農業】建物を二枚以上所有しているなら+22点",
  export_port_bonus: "終了時【工業】建物を二枚以上所有しているなら+24点",
  investment_bank_bonus: "終了時【鍵】建物を4枚以上所有しているなら+30点",
  passive_double_vp: "勝利点トークンから2倍の得点",
  passive: "所持するだけで得点",
};

/**
 * 初期共有カード (ゲーム開始時にテーブルに出現)
 */
export const INITIAL_PUBLIC_CARDS = [
  ALL_CARDS.find((c) => c.id === "quarry")!,
  ALL_CARDS.find((c) => c.id === "mine")!,
  ALL_CARDS.find((c) => c.id === "school")!,
  ALL_CARDS.find((c) => c.id === "carpenter")!,
];

/**
 * 初期プレイヤーカード (各プレイヤーがゲーム開始時に持つカード)
 */
export const INITIAL_PLAYER_CARDS: Card[] = [];

/**
 * ゲーム定数
 */
export const GAME_CONFIG = {
  MIN_PLAYERS: 2,
  MAX_PLAYERS: 4,
  STARTING_COINS: 5,
  STARTING_FOOD: 0,
  MAX_HAND_SIZE: 10,
  INITIAL_ROUND: 1,
  TOTAL_ROUNDS: 9,
  MIN_WORKERS: 2,
  MAX_WORKERS: 5,
  UNPAID_DEBT_PENALTY: 3, // 未払い賃金1枚=-3点
};

/**
 * ラウンドカード定義（ラウンドごとの賃金レート）
 */
export const ROUND_CARDS: RoundCard[] = [
  {
    round: 1,
    wagePerWorker: 2,
    newPublicBuildingIds: [], // 初期4枚は INITIAL_PUBLIC_CARDS で配置
  },
  { round: 2, wagePerWorker: 1, newPublicBuildingIds: ["shop"] },
  { round: 3, wagePerWorker: 2, newPublicBuildingIds: ["market"] },
  { round: 4, wagePerWorker: 3, newPublicBuildingIds: ["high_school"] },
  { round: 5, wagePerWorker: 2, newPublicBuildingIds: ["supermarket"] },
  { round: 6, wagePerWorker: 4, newPublicBuildingIds: ["university"] },
  { round: 7, wagePerWorker: 3, newPublicBuildingIds: ["department_store"] },
  {
    round: 8,
    wagePerWorker: 5,
    newPublicBuildingIds: ["vocational_school", "expo"],
  },
  { round: 9, wagePerWorker: 2, newPublicBuildingIds: [] },
];
