/**
 * Game Cards Definition
 * ゲーム全体のカード定義
 */

import type { Card, RoundCard } from "@/lib/types";

export const ALL_CARDS: Card[] = [
  // === 初期公共職場（ラウンド1から利用可能） ===
  {
    id: "quarry",
    name: "採石場",
    cost: 0,
    effect: "draw_card_1",
    cardType: "building",
    assetValue: 3,
    category: "public",
    icon: "⛏️",
  },
  {
    id: "mine",
    name: "鉱山",
    cost: 0,
    effect: "gain_coins_6_multi",
    cardType: "building",
    assetValue: 4,
    category: "public",
    icon: "⛰️",
    allowMultipleWorkers: true,
  },
  {
    id: "school",
    name: "学校",
    cost: 0,
    effect: "hire_worker_training",
    cardType: "building",
    assetValue: 4,
    category: "public",
    icon: "🏫",
  },
  {
    id: "carpenter",
    name: "大工",
    cost: 0,
    effect: "build_card",
    cardType: "building",
    assetValue: 3,
    category: "public",
    icon: "🪚",
  },

  // === ラウンド追加公共職場 ===
  {
    id: "shop",
    name: "露店",
    cost: 0,
    effect: "gain_coins_6",
    cardType: "building",
    assetValue: 2,
    category: "public",
    icon: "🏪",
  },
  {
    id: "market",
    name: "市場",
    cost: 0,
    effect: "gain_coins_12",
    cardType: "building",
    assetValue: 5,
    category: "public",
    icon: "🛒",
  },
  {
    id: "high_school",
    name: "高等学校",
    cost: 0,
    effect: "hire_to_4_workers",
    cardType: "building",
    assetValue: 6,
    category: "public",
    icon: "🎓",
  },
  {
    id: "supermarket",
    name: "スーパーマーケット",
    cost: 0,
    effect: "gain_coins_18",
    cardType: "building",
    assetValue: 8,
    category: "public",
    icon: "🏬",
  },
  {
    id: "university",
    name: "大学",
    cost: 0,
    effect: "hire_to_5_workers",
    cardType: "building",
    assetValue: 10,
    category: "public",
    icon: "🎓",
  },
  {
    id: "department_store",
    name: "百貨店",
    cost: 0,
    effect: "gain_coins_24",
    cardType: "building",
    assetValue: 12,
    category: "public",
    icon: "🏢",
  },
  {
    id: "vocational_school",
    name: "専門学校",
    cost: 0,
    effect: "hire_worker_instant",
    cardType: "building",
    assetValue: 8,
    category: "public",
    icon: "🏫",
  },
  {
    id: "expo",
    name: "万博",
    cost: 0,
    effect: "gain_coins_30",
    cardType: "building",
    assetValue: 15,
    category: "public",
    icon: "🎪",
  },

  // === プレイヤー建物カード（私有職場） ===
  // 合計73枚、26種類
  // 菜園（4枚）
  {
    id: "vegetable_garden_1",
    name: "菜園",
    cost: 4,
    effect: "gain_goods_2_vp_1",
    cardType: "building",
    assetValue: 2,
    category: "private",
    icon: "🌱",
  },
  {
    id: "vegetable_garden_2",
    name: "菜園",
    cost: 4,
    effect: "gain_goods_2_vp_1",
    cardType: "building",
    assetValue: 2,
    category: "private",
    icon: "🌱",
  },
  {
    id: "vegetable_garden_3",
    name: "菜園",
    cost: 4,
    effect: "gain_goods_2_vp_1",
    cardType: "building",
    assetValue: 2,
    category: "private",
    icon: "🌱",
  },
  {
    id: "vegetable_garden_4",
    name: "菜園",
    cost: 4,
    effect: "gain_goods_2_vp_1",
    cardType: "building",
    assetValue: 2,
    category: "private",
    icon: "🌱",
  },
  // 鉄工所（3枚）
  {
    id: "ironworks_1",
    name: "鉄工所",
    cost: 6,
    effect: "draw_card_2_need_mine",
    cardType: "building",
    assetValue: 6,
    category: "private",
    icon: "🏭",
  },
  {
    id: "ironworks_2",
    name: "鉄工所",
    cost: 6,
    effect: "draw_card_2_need_mine",
    cardType: "building",
    assetValue: 6,
    category: "private",
    icon: "🏭",
  },
  {
    id: "ironworks_3",
    name: "鉄工所",
    cost: 6,
    effect: "draw_card_2_need_mine",
    cardType: "building",
    assetValue: 6,
    category: "private",
    icon: "🏭",
  },
  // 宝くじ（3枚）
  {
    id: "lottery_1",
    name: "宝くじ",
    cost: 8,
    effect: "gain_coins_20_pay_10",
    cardType: "building",
    assetValue: 4,
    category: "private",
    icon: "🎰",
  },
  {
    id: "lottery_2",
    name: "宝くじ",
    cost: 8,
    effect: "gain_coins_20_pay_10",
    cardType: "building",
    assetValue: 4,
    category: "private",
    icon: "🎰",
  },
  {
    id: "lottery_3",
    name: "宝くじ",
    cost: 8,
    effect: "gain_coins_20_pay_10",
    cardType: "building",
    assetValue: 4,
    category: "private",
    icon: "🎰",
  },
  // 遊園地（2枚）
  {
    id: "amusement_park_1",
    name: "遊園地",
    cost: 12,
    effect: "gain_coins_25",
    cardType: "building",
    assetValue: 12,
    category: "private",
    icon: "🎢",
  },
  {
    id: "amusement_park_2",
    name: "遊園地",
    cost: 12,
    effect: "gain_coins_25",
    cardType: "building",
    assetValue: 12,
    category: "private",
    icon: "🎢",
  },
  // 芋畑（4枚）
  {
    id: "potato_field_1",
    name: "芋畑",
    cost: 5,
    effect: "gain_goods_hand_size",
    cardType: "building",
    assetValue: 3,
    category: "private",
    icon: "🥔",
  },
  {
    id: "potato_field_2",
    name: "芋畑",
    cost: 5,
    effect: "gain_goods_hand_size",
    cardType: "building",
    assetValue: 3,
    category: "private",
    icon: "🥔",
  },
  {
    id: "potato_field_3",
    name: "芋畑",
    cost: 5,
    effect: "gain_goods_hand_size",
    cardType: "building",
    assetValue: 3,
    category: "private",
    icon: "🥔",
  },
  {
    id: "potato_field_4",
    name: "芋畑",
    cost: 5,
    effect: "gain_goods_hand_size",
    cardType: "building",
    assetValue: 3,
    category: "private",
    icon: "🥔",
  },
  // 観光牧場（3枚）
  {
    id: "tourist_farm_1",
    name: "観光牧場",
    cost: 8,
    effect: "gain_coins_4_per_good",
    cardType: "building",
    assetValue: 8,
    category: "private",
    icon: "🐄",
  },
  {
    id: "tourist_farm_2",
    name: "観光牧場",
    cost: 8,
    effect: "gain_coins_4_per_good",
    cardType: "building",
    assetValue: 8,
    category: "private",
    icon: "🐄",
  },
  {
    id: "tourist_farm_3",
    name: "観光牧場",
    cost: 8,
    effect: "gain_coins_4_per_good",
    cardType: "building",
    assetValue: 8,
    category: "private",
    icon: "🐄",
  },
  // 建築会社（3枚）
  {
    id: "construction_company_1",
    name: "建築会社",
    cost: 10,
    effect: "build_facility_draw_2",
    cardType: "building",
    assetValue: 10,
    category: "private",
    icon: "🏗️",
  },
  {
    id: "construction_company_2",
    name: "建築会社",
    cost: 10,
    effect: "build_facility_draw_2",
    cardType: "building",
    assetValue: 10,
    category: "private",
    icon: "🏗️",
  },
  {
    id: "construction_company_3",
    name: "建築会社",
    cost: 10,
    effect: "build_facility_draw_2",
    cardType: "building",
    assetValue: 10,
    category: "private",
    icon: "🏗️",
  },
  // 研究所（3枚）
  {
    id: "research_lab_1",
    name: "研究所",
    cost: 12,
    effect: "draw_card_2_vp_1",
    cardType: "building",
    assetValue: 12,
    category: "private",
    icon: "🔬",
  },
  {
    id: "research_lab_2",
    name: "研究所",
    cost: 12,
    effect: "draw_card_2_vp_1",
    cardType: "building",
    assetValue: 12,
    category: "private",
    icon: "🔬",
  },
  {
    id: "research_lab_3",
    name: "研究所",
    cost: 12,
    effect: "draw_card_2_vp_1",
    cardType: "building",
    assetValue: 12,
    category: "private",
    icon: "🔬",
  },
  // 食品工場（4枚）★
  {
    id: "food_factory_1",
    name: "食品工場",
    cost: 14,
    effect: "discard_2_draw_4",
    cardType: "building",
    assetValue: 14,
    category: "private",
    icon: "🏭",
  },
  {
    id: "food_factory_2",
    name: "食品工場",
    cost: 14,
    effect: "discard_2_draw_4",
    cardType: "building",
    assetValue: 14,
    category: "private",
    icon: "🏭",
  },
  {
    id: "food_factory_3",
    name: "食品工場",
    cost: 14,
    effect: "discard_2_draw_4",
    cardType: "building",
    assetValue: 14,
    category: "private",
    icon: "🏭",
  },
  {
    id: "food_factory_4",
    name: "食品工場",
    cost: 14,
    effect: "discard_2_draw_4",
    cardType: "building",
    assetValue: 14,
    category: "private",
    icon: "🏭",
  },
  // 醸造所（3枚）
  {
    id: "brewery_1",
    name: "醸造所",
    cost: 16,
    effect: "draw_goods_4_next_round",
    cardType: "building",
    assetValue: 16,
    category: "private",
    icon: "🍺",
  },
  {
    id: "brewery_2",
    name: "醸造所",
    cost: 16,
    effect: "draw_goods_4_next_round",
    cardType: "building",
    assetValue: 16,
    category: "private",
    icon: "🍺",
  },
  {
    id: "brewery_3",
    name: "醸造所",
    cost: 16,
    effect: "draw_goods_4_next_round",
    cardType: "building",
    assetValue: 16,
    category: "private",
    icon: "🍺",
  },
  // 地球建設（2枚）
  {
    id: "land_development_1",
    name: "地球建設",
    cost: 18,
    effect: "build_2_draw_3",
    cardType: "building",
    assetValue: 18,
    category: "private",
    icon: "🌍",
  },
  {
    id: "land_development_2",
    name: "地球建設",
    cost: 18,
    effect: "build_2_draw_3",
    cardType: "building",
    assetValue: 18,
    category: "private",
    icon: "🌍",
  },
  // 石油コンビナート（3枚）
  {
    id: "oil_complex_1",
    name: "石油コンビナート",
    cost: 20,
    effect: "draw_card_4",
    cardType: "building",
    assetValue: 20,
    category: "private",
    icon: "🛢️",
  },
  {
    id: "oil_complex_2",
    name: "石油コンビナート",
    cost: 20,
    effect: "draw_card_4",
    cardType: "building",
    assetValue: 20,
    category: "private",
    icon: "🛢️",
  },
  {
    id: "oil_complex_3",
    name: "石油コンビナート",
    cost: 20,
    effect: "draw_card_4",
    cardType: "building",
    assetValue: 20,
    category: "private",
    icon: "🛢️",
  },
  // 大聖堂（2枚）
  {
    id: "cathedral_building_1",
    name: "大聖堂",
    cost: 24,
    effect: "none",
    cardType: "building",
    assetValue: 24,
    category: "private",
    icon: "⛪",
  },
  {
    id: "cathedral_building_2",
    name: "大聖堂",
    cost: 24,
    effect: "none",
    cardType: "building",
    assetValue: 24,
    category: "private",
    icon: "⛪",
  },
  // 宮大工（4枚）
  {
    id: "palace_carpenter_1",
    name: "宮大工",
    cost: 12,
    effect: "build_card_vp_1",
    cardType: "building",
    assetValue: 12,
    category: "private",
    icon: "🏛️",
  },
  {
    id: "palace_carpenter_2",
    name: "宮大工",
    cost: 12,
    effect: "build_card_vp_1",
    cardType: "building",
    assetValue: 12,
    category: "private",
    icon: "🏛️",
  },
  {
    id: "palace_carpenter_3",
    name: "宮大工",
    cost: 12,
    effect: "build_card_vp_1",
    cardType: "building",
    assetValue: 12,
    category: "private",
    icon: "🏛️",
  },
  {
    id: "palace_carpenter_4",
    name: "宮大工",
    cost: 12,
    effect: "build_card_vp_1",
    cardType: "building",
    assetValue: 12,
    category: "private",
    icon: "🏛️",
  },
  // 造船所（3枚）
  {
    id: "shipyard_1",
    name: "造船所",
    cost: 18,
    effect: "discard_3_draw_6",
    cardType: "building",
    assetValue: 18,
    category: "private",
    icon: "⚓",
  },
  {
    id: "shipyard_2",
    name: "造船所",
    cost: 18,
    effect: "discard_3_draw_6",
    cardType: "building",
    assetValue: 18,
    category: "private",
    icon: "⚓",
  },
  {
    id: "shipyard_3",
    name: "造船所",
    cost: 18,
    effect: "discard_3_draw_6",
    cardType: "building",
    assetValue: 18,
    category: "private",
    icon: "⚓",
  },
  // 工業団地（3枚）
  {
    id: "industrial_park_1",
    name: "工業団地",
    cost: 15,
    effect: "draw_card_3",
    cardType: "building",
    assetValue: 15,
    category: "private",
    icon: "🏭",
  },
  {
    id: "industrial_park_2",
    name: "工業団地",
    cost: 15,
    effect: "draw_card_3",
    cardType: "building",
    assetValue: 15,
    category: "private",
    icon: "🏭",
  },
  {
    id: "industrial_park_3",
    name: "工業団地",
    cost: 15,
    effect: "draw_card_3",
    cardType: "building",
    assetValue: 15,
    category: "private",
    icon: "🏭",
  },
  // 食堂（3枚）
  {
    id: "cafeteria_1",
    name: "食堂",
    cost: 6,
    effect: "gain_coins_8",
    cardType: "building",
    assetValue: 6,
    category: "private",
    icon: "�️",
  },
  {
    id: "cafeteria_2",
    name: "食堂",
    cost: 6,
    effect: "gain_coins_8",
    cardType: "building",
    assetValue: 6,
    category: "private",
    icon: "🍽️",
  },
  {
    id: "cafeteria_3",
    name: "食堂",
    cost: 6,
    effect: "gain_coins_8",
    cardType: "building",
    assetValue: 6,
    category: "private",
    icon: "🍽️",
  },
  // プレハブ工務店（3枚）
  {
    id: "prefab_contractor_1",
    name: "プレハブ工務店",
    cost: 12,
    effect: "build_free_under_10",
    cardType: "building",
    assetValue: 12,
    category: "private",
    icon: "�️",
  },
  {
    id: "prefab_contractor_2",
    name: "プレハブ工務店",
    cost: 12,
    effect: "build_free_under_10",
    cardType: "building",
    assetValue: 12,
    category: "private",
    icon: "🏗️",
  },
  {
    id: "prefab_contractor_3",
    name: "プレハブ工務店",
    cost: 12,
    effect: "build_free_under_10",
    cardType: "building",
    assetValue: 12,
    category: "private",
    icon: "🏗️",
  },
  // 養殖場（4枚）★
  {
    id: "fish_farm_1",
    name: "養殖場",
    cost: 10,
    effect: "draw_goods_2_or_3",
    cardType: "building",
    assetValue: 10,
    category: "private",
    icon: "🐟",
  },
  {
    id: "fish_farm_2",
    name: "養殖場",
    cost: 10,
    effect: "draw_goods_2_or_3",
    cardType: "building",
    assetValue: 10,
    category: "private",
    icon: "🐟",
  },
  {
    id: "fish_farm_3",
    name: "養殖場",
    cost: 10,
    effect: "draw_goods_2_or_3",
    cardType: "building",
    assetValue: 10,
    category: "private",
    icon: "🐟",
  },
  {
    id: "fish_farm_4",
    name: "養殖場",
    cost: 10,
    effect: "draw_goods_2_or_3",
    cardType: "building",
    assetValue: 10,
    category: "private",
    icon: "🐟",
  },

  // === 終了時ボーナス建物 ===
  // 旧市街（2枚）
  {
    id: "old_town_1",
    name: "旧市街",
    cost: 8,
    effect: "none",
    cardType: "building",
    assetValue: 8,
    category: "private",
    icon: "🏘️",
  },
  {
    id: "old_town_2",
    name: "旧市街",
    cost: 8,
    effect: "none",
    cardType: "building",
    assetValue: 8,
    category: "private",
    icon: "🏘️",
  },
  // 会計事務所（2枚）
  {
    id: "accounting_office_1",
    name: "会計事務所",
    cost: 10,
    effect: "none",
    cardType: "building",
    assetValue: 10,
    category: "private",
    endGameBonus: "accounting_office",
    icon: "📊",
  },
  {
    id: "accounting_office_2",
    name: "会計事務所",
    cost: 10,
    effect: "none",
    cardType: "building",
    assetValue: 10,
    category: "private",
    endGameBonus: "accounting_office",
    icon: "📊",
  },
  // 墓地（2枚）
  {
    id: "graveyard_1",
    name: "墓地",
    cost: 8,
    effect: "none",
    cardType: "building",
    assetValue: 8,
    category: "private",
    endGameBonus: "graveyard",
    icon: "🪦",
  },
  {
    id: "graveyard_2",
    name: "墓地",
    cost: 8,
    effect: "none",
    cardType: "building",
    assetValue: 8,
    category: "private",
    endGameBonus: "graveyard",
    icon: "🪦",
  },
  // 輸出港（2枚）
  {
    id: "export_port_1",
    name: "輸出港",
    cost: 24,
    effect: "none",
    cardType: "building",
    assetValue: 24,
    category: "private",
    endGameBonus: "export_port",
    icon: "🚢",
  },
  {
    id: "export_port_2",
    name: "輸出港",
    cost: 24,
    effect: "none",
    cardType: "building",
    assetValue: 24,
    category: "private",
    endGameBonus: "export_port",
    icon: "🚢",
  },
  // 鉄道駅（2枚）
  {
    id: "train_station_1",
    name: "鉄道駅",
    cost: 18,
    effect: "none",
    cardType: "building",
    assetValue: 18,
    category: "private",
    endGameBonus: "train_station",
    icon: "🚉",
  },
  {
    id: "train_station_2",
    name: "鉄道駅",
    cost: 18,
    effect: "none",
    cardType: "building",
    assetValue: 18,
    category: "private",
    endGameBonus: "train_station",
    icon: "🚉",
  },
  // 投資銀行（2枚）
  {
    id: "investment_bank_1",
    name: "投資銀行",
    cost: 30,
    effect: "none",
    cardType: "building",
    assetValue: 30,
    category: "private",
    endGameBonus: "investment_bank",
    icon: "🏦",
  },
  {
    id: "investment_bank_2",
    name: "投資銀行",
    cost: 30,
    effect: "none",
    cardType: "building",
    assetValue: 30,
    category: "private",
    endGameBonus: "investment_bank",
    icon: "🏦",
  },
  // 植物園（2枚）
  {
    id: "botanical_garden_1",
    name: "植物園",
    cost: 22,
    effect: "none",
    cardType: "building",
    assetValue: 22,
    category: "private",
    endGameBonus: "botanical_garden",
    icon: "🌺",
  },
  {
    id: "botanical_garden_2",
    name: "植物園",
    cost: 22,
    effect: "none",
    cardType: "building",
    assetValue: 22,
    category: "private",
    endGameBonus: "botanical_garden",
    icon: "🌺",
  },
];

// === 消費財カード（30枚） ===
export const CONSUMABLE_CARDS: Card[] = Array.from({ length: 30 }, (_, i) => ({
  id: `goods_${i + 1}`,
  name: "消費財",
  cost: 0,
  effect: "none",
  cardType: "goods",
  icon: "📦",
}));

// カード効果の説明
export const CARD_EFFECT_DESCRIPTIONS: Record<string, string> = {
  // 公共職場
  draw_card_1: "建物カード1枚引く",
  gain_coins_6_multi: "1枚捨て→$6（複数回可）",
  hire_worker_training: "労働者+1（研修中、次ラウンドから）",
  build_card: "手札から建物を建てる",
  gain_coins_6: "1枚捨て→$6（家計から）",
  gain_coins_12: "2枚捨て→$12（家計から）",
  hire_to_4_workers: "労働者を4人にする",
  gain_coins_18: "2枚捨て→$18（家計から）",
  hire_to_5_workers: "労働者を5人にする",
  gain_coins_24: "3枚捨て→$24（家計から）",
  hire_worker_instant: "労働者+1（即座に使える）",
  gain_coins_30: "3枚捨て→$30（家計から）",

  // 私有職場
  gain_goods_2_vp_1: "消費財2枚+勝利点トークン1枚",
  draw_card_2_need_mine: "建物カード2枚引く（鉱山に配置必要）",
  gain_coins_20_pay_10: "家計から$20取り、$10返す",
  gain_coins_25: "家計から$25取る",
  gain_goods_hand_size: "手札0枚→消費財3枚、1枚→2枚、2枚→1枚",
  gain_coins_4_per_good: "手札の消費財1枚につき$4",
  build_facility_draw_2: "施設建物を建て、カード2枚引く",
  draw_card_2_vp_1: "建物カード2枚+勝利点トークン1枚",
  discard_2_draw_4: "手札2枚捨て→建物カード4枚",
  draw_goods_4_next_round: "消費財4枚（次ラウンド開始時に手札へ）",
  build_2_draw_3: "建物2つ建て、手札空なら3枚引く",
  draw_card_4: "建物カード4枚引く",
  none: "特殊効果なし（得点のみ）",
  build_card_vp_1: "建物を建て、勝利点トークン1枚",
  discard_3_draw_6: "手札3枚捨て→建物カード6枚",
  draw_card_3: "建物カード3枚引く",
  gain_coins_8: "家計から$8取る",
  build_free_under_10: "資産価値$10以下の建物を無料で建てる",
  gain_goods_2or3: "消費財なし→2枚、あり→3枚",

  // 終了時ボーナス
  passive_double_vp: "勝利点トークンから2倍の得点",
  passive: "所持するだけで得点",
};

/**
 * 初期共有カード (ゲーム開始時にテーブルに出現)
 */
export const INITIAL_PUBLIC_CARDS = [
  ALL_CARDS.find((c) => c.id === "quarry")!,
  ALL_CARDS.find((c) => c.id === "mine")!,
  ALL_CARDS.find((c) => c.id === "school")!,
  ALL_CARDS.find((c) => c.id === "carpenter")!,
];

/**
 * 初期プレイヤーカード (各プレイヤーがゲーム開始時に持つカード)
 */
export const INITIAL_PLAYER_CARDS: Card[] = [];

/**
 * ゲーム定数
 */
export const GAME_CONFIG = {
  MIN_PLAYERS: 2,
  MAX_PLAYERS: 4,
  STARTING_COINS: 5,
  STARTING_FOOD: 0,
  MAX_HAND_SIZE: 10,
  INITIAL_ROUND: 1,
  TOTAL_ROUNDS: 9,
  MIN_WORKERS: 2,
  MAX_WORKERS: 5,
  UNPAID_DEBT_PENALTY: 3, // 未払い賃金1枚=-3点
};

/**
 * ラウンドカード定義（ラウンドごとの賃金レート）
 */
export const ROUND_CARDS: RoundCard[] = [
  {
    round: 1,
    wagePerWorker: 2,
    newPublicBuildingIds: [], // 初期4枚は INITIAL_PUBLIC_CARDS で配置
  },
  { round: 2, wagePerWorker: 1, newPublicBuildingIds: ["shop"] },
  { round: 3, wagePerWorker: 2, newPublicBuildingIds: ["market"] },
  { round: 4, wagePerWorker: 3, newPublicBuildingIds: ["high_school"] },
  { round: 5, wagePerWorker: 2, newPublicBuildingIds: ["supermarket"] },
  { round: 6, wagePerWorker: 4, newPublicBuildingIds: ["university"] },
  { round: 7, wagePerWorker: 3, newPublicBuildingIds: ["department_store"] },
  {
    round: 8,
    wagePerWorker: 5,
    newPublicBuildingIds: ["vocational_school", "expo"],
  },
  { round: 9, wagePerWorker: 2, newPublicBuildingIds: [] },
];
